# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_C2(object):
    def setupUi(self, C2):
        C2.setObjectName("C2")
        C2.resize(786, 439)
        self.centralwidget = QtWidgets.QWidget(C2)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 90, 291, 241))
        self.pushButton.setObjectName("pushButton")
        C2.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(C2)
        self.statusbar.setObjectName("statusbar")
        C2.setStatusBar(self.statusbar)

        self.retranslateUi(C2)
        QtCore.QMetaObject.connectSlotsByName(C2)

    def retranslateUi(self, C2):
        _translate = QtCore.QCoreApplication.translate
        C2.setWindowTitle(_translate("C2", "2C"))
        self.pushButton.setText(_translate("C2", "PushButton"))
